name: CI/CD Pipeline - Code Quality and Security

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analyze_and_check_quality:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      checks: write 
      pull-requests: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      
      - name: Set up JDK 17 (Example for Java projects)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      # ----------------------------------------------------------------------
      # 1. Run SonarQube Analysis (Requires correct SONAR_HOST_URL format)
      # ----------------------------------------------------------------------
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: ${{ github.workspace }}
          args: >
            -Dsonar.projectKey=jeshualexi_essiem
            -Dsonar.sources=.
            -Dsonar.organization=jeshualexi
            -Dsonar.qualitygate.wait=true 

  
          
      # ----------------------------------------------------------------------
      # 3. Run SOOS SCA Analysis
      # ----------------------------------------------------------------------
      - name: SOOS Software Composition Analysis (SCA)
        uses: soos-io/soos-sca-github-action@b73d8502a2121bdcc40be9e05ee656d21f76b771
        env:
          SOOS_CLIENT_ID: ${{ secrets.SOOS_CLIENT_ID }}
          SOOS_API_KEY: ${{ secrets.SOOS_API_KEY }}
        with:
          project_name: 'My-SOOS-Project'
          branch_name: ${{ github.ref_name }}

      
