name: CI/CD Pipeline - Code Quality and Security

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analyze_and_check_quality:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # Required by SonarQube Quality Gate Check to update PR status
      checks: write 
      pull-requests: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Disabling shallow clone is crucial for a full SonarQube analysis
          fetch-depth: 0 
      
      - name: Set up JDK 17 (Example for Java projects)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      # ----------------------------------------------------------------------
      # 1. Run SonarQube Analysis (Using stable @master tag)
      # ----------------------------------------------------------------------
      - name: SonarQube Analysis
        # Note: Using @master or a specific version like @v2 is recommended 
        # over @main to avoid "unable to find version" errors.
        uses: SonarSource/sonarqube-scan-action@master 
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: ${{ github.workspace }}
          args: >
            -Dsonar.projectKey=YOUR_PROJECT_KEY
            -Dsonar.sources=.

      # ----------------------------------------------------------------------
      # 2. Check SonarQube Quality Gate Status (Using stable @master tag)
      # ----------------------------------------------------------------------
      - name: SonarQube Quality Gate Check
        id: quality_gate_check
        uses: SonarSource/sonarqube-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          
      # ----------------------------------------------------------------------
      # 3. Run SOOS SCA Analysis (CORRECTED ACTION NAME)
      # ----------------------------------------------------------------------
      - name: SOOS Software Composition Analysis (SCA)
        # The correct repository is 'soos-sca-github-action'. Using the latest major version tag.
        uses: soos-io/soos-sca-github-action@v2
        env:
          SOOS_CLIENT_ID: ${{ secrets.SOOS_CLIENT_ID }}
          SOOS_API_KEY: ${{ secrets.SOOS_API_KEY }}
        with:
          project_name: 'My-SOOS-Project'
          branch_name: ${{ github.ref_name }}

      # ----------------------------------------------------------------------
      # 4. Fail the build if the Quality Gate is NOT GREEN
      # ----------------------------------------------------------------------
      - name: Fail build on Quality Gate failure
        if: steps.quality_gate_check.outputs.quality-gate-status != 'OK'
        run: |
          echo "SonarQube Quality Gate did not pass. Failing the build."
          exit 1
