name: CI/CD Pipeline - Code Quality and Security

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analyze_and_check_quality:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      checks: write 
      pull-requests: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      
      - name: Set up JDK 17 (Example for Java projects)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      # ----------------------------------------------------------------------
      # 1. Run SonarQube Analysis (Requires correct SONAR_HOST_URL format)
      # ----------------------------------------------------------------------
      - name: SonarQube Analysis
        uses: SonarSource/sonarqube-scan-action@cf038b0e0cdecfa9e56c198bbb7d21d751d62c3b
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: ${{ github.workspace }}
          args: >
            -Dsonar.projectKey=jeshualexi_essiem
            -Dsonar.sources=.
            -Dsonar.organization=jeshualexi

      # ----------------------------------------------------------------------
      # 2. Check SonarQube Quality Gate Status
      # ----------------------------------------------------------------------
      - name: SonarQube Quality Gate Check
        id: quality_gate_check
        uses: SonarSource/sonarqube-quality-gate-action@cf038b0e0cdecfa9e56c198bbb7d21d751d62c3b
        env:
          # This step also relies on the correctly formatted SONAR_HOST_URL
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          
      # ----------------------------------------------------------------------
      # 3. Run SOOS SCA Analysis
      # ----------------------------------------------------------------------
      - name: SOOS Software Composition Analysis (SCA)
        uses: soos-io/soos-sca-github-action@616909ecb474a9d86d6470d6b4a0ac16b33d6f4d
        env:
          SOOS_CLIENT_ID: ${{ secrets.SOOS_CLIENT_ID }}
          SOOS_API_KEY: ${{ secrets.SOOS_API_KEY }}
        with:
          project_name: 'My-SOOS-Project'
          branch_name: ${{ github.ref_name }}

      # ----------------------------------------------------------------------
      # 4. Fail the build if the Quality Gate is NOT GREEN
      # ----------------------------------------------------------------------
      - name: Fail build on Quality Gate failure
        if: steps.quality_gate_check.outputs.quality-gate-status != 'OK'
        run: |
          echo "SonarQube Quality Gate did not pass. Failing the build."
          exit 1
